### ISSUE TITLE
为什么会有这个问题？

### ISSUE THREAD

**Issue by HLKunn** [Sharpiless/Yolov5-deepsort-inference#25]
Traceback (most recent call last):
  File "E:/TuXiangChuLi/week14/Yolov5-deepsort-inference/demo.py", line 1, in <module>
    from AIDetector_pytorch import Detector
  File "E:\TuXiangChuLi\week14\Yolov5-deepsort-inference\AIDetector_pytorch.py", line 6, in <module>
    from utils.BaseDetector import baseDet
  File "E:\TuXiangChuLi\week14\Yolov5-deepsort-inference\utils\BaseDetector.py", line 1, in <module>
    from tracker import update_tracker
  File "E:\TuXiangChuLi\week14\Yolov5-deepsort-inference\tracker.py", line 8, in <module>
    cfg.merge_from_file("E:/TuXiangChuLi/week14/Yolov5-deepsort-inference/deep_sort/configs/deep_sort.yaml")
  File "E:\TuXiangChuLi\week14\Yolov5-deepsort-inference\deep_sort\utils\parser.py", line 23, in merge_from_file
    self.update(yaml.load(fo.read()))
TypeError: load() missing 1 required positional argument: 'Loader'

Process finished with exit code 1

**Comment by eedasdgfy** [comment]
我也是这个问题
